apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: prod
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Paris
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: RECOMMENDATION_PORT
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: PRODUCT_CATALOG_SERVICE_ADDR
          image: gcr.io/formationgcp/prod/recommendation-service:latest
          imagePullPolicy: Always
          name: recommendationservice
          ports:
            - containerPort: 8080
          resources:
            {}
            # requests:
            #   cpu: "100m"
            #   memory: "512Mi"
            # limits:
            #   cpu: "100m"
            #   memory: "512Mi"
          stdin: true
          tty: true
      securityContext:
        runAsUser: 0
      serviceAccountName: ""
status: {}
