apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: prod
  labels:
    app: shippingservice
spec:
  ports:
    - name: "50051"
      port: 50051
      targetPort: 50051
  type: ClusterIP
  selector:
    app: shippingservice