apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: paymentservice
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paymentservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60