apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: prod
  labels:
    app: paymentservice
spec:
  ports:
    - name: "50052"
      port: 50052
      targetPort: 50051
  type: ClusterIP
  selector:
    app: paymentservice