apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Paris
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: PRODUCT_CATALOG_SERVICE_ADDR
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: SHIPPING_SERVICE_ADDR
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: CART_SERVICE_ADDR
            - name: CURRENCY_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: CURRENCY_SERVICE_ADDR
            - name: CHECKOUT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: CHECKOUT_SERVICE_ADDR
            - name: RECOMMENDATION_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: RECOMMENDATION_SERVICE_ADDR
            - name: AD_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: AD_SERVICE_ADDR
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: FRONTEND_PORT
          image: gcr.io/formationgcp/prod/frontend:latest
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8080
          resources:
            {}
            # requests:
            #   cpu: "100m"
            #   memory: "512Mi"
            # limits:
            #   cpu: "100m"
            #   memory: "512Mi"
          stdin: true
          tty: true
      securityContext:
        runAsUser: 0
      serviceAccountName: ""
status: {}
