apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prod
  labels:
    app: frontend
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: frontend