apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: prod
  labels:
    app: cartservice
spec:
  ports:
    - name: "7070"
      port: 7070
      targetPort: 7070
  type: ClusterIP
  selector:
    app: cartservice
