apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: prod
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Paris
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: prod-config-map
                  key: EMAIL_SERVICE_PORT
          image: gcr.io/formationgcp/prod/email-service:latest
          imagePullPolicy: Always
          name: emailservice
          ports:
            - containerPort: 8080
          resources:
            {}
            # requests:
            #   cpu: "100m"
            #   memory: "512Mi"
            # limits:
            #   cpu: "100m"
            #   memory: "512Mi"
          stdin: true
          tty: true
      securityContext:
        runAsUser: 0
      serviceAccountName: ""
status: {}
