apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: prod
  labels:
    app: emailservice
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 8080
  type: ClusterIP
  selector:
    app: emailservice