apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: prod
  labels:
    app: currencyservice
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
  type: ClusterIP
  selector:
    app: currencyservice