apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: prod
  labels:
    app: adservice
spec:
  ports:
    - name: "9555"
      port: 9555
      targetPort: 9555
  type: ClusterIP
  selector:
    app: adservice
