apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: prod
  labels:
    app: productcatalogservice
spec:
  ports:
    - name: "3550"
      port: 3550
      targetPort: 3550
  type: ClusterIP
  selector:
    app: productcatalogservice