apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: prod
  labels:
    app: loadgenerator
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  type: ClusterIP
  selector:
    app: loadgenerator